extra:
  generator: false
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - PS:
    - ps.md
    - Kombinatorika: ps-comb.md
    - Pravděpodobnost: ps-prob.md
    - Náhodná veličina: ps-rand-var.md
    - Diskrétní náhodná veličina: ps-dnv.md
    - Čebyševova nerovnost: ps-cebyshev.md
  - PvR:
    - pvr.md
    - Fizz buzz: pvr-fizz.md
  - AI:
    - HTML: ai-html.md
  - Skripty:
    - Prohlížeč: sc-browser.md
    - Windows: sc-windows.md
plugins:
  - offline
  - search
site_name: Poznámky
theme:
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
  footer:
    icon: null
    copyright: ""
  language: cs
  name: material
watch:
  - overrides
